# do a trace (get more output to log), true or false
do_trace = true

# file that you write your log to
own_log = "/var/log/yourCryptoBot.log"

# location of gctcli command
gctcmd = "/home/pi/git/gocryptotrader/cmd/gctcli/gctcli"
gctuser = "admin"
gctpassword = "Password"

# list of exchanges
exchanges = [
  "binance"
]

# list of pairs
pairs = [
  "BNB-EUR",
  "XLM-EUR",
  "GRT-EUR",
  "WRX-EUR"
]
