# do a trace (get more output to log), true or false
do_trace = false

# sleep before candles are fetched
sleepbeforerun = 0

# location of gctcli command
gctcmd = "/home/pi/git/yourCryptoBot/exchanges/binance/binance"
bkpcmd = "/home/pi/git/gocryptotrader/cmd/gctcli/gctcli"

wwwpath = "/var/www/html/"

# quote currency
curr_quote = "EUR"

# BTC reference
btcref = true

pguser = ""
pgpassword = ""
pgdb = "yourBot"

tbtoken = ""

key_issuer = ""
key_account = ""
key_secret = ""

apikey = ""
apisecret = ""
apiclient = ""

# name of exchange
exchange_name = "binance"

# list of pairs
pairs = [
  "BTC-EUR",
  "BNB-EUR",
  "XLM-EUR",
  "GRT-EUR",
  "ETH-EUR",
  "XRP-EUR",
  "LUNA-EUR",
  "EOS-EUR",
  "DOT-EUR",
  "THETA-EUR",
  "CHZ-EUR",
  "ADA-EUR",
  "ENJ-EUR",
  "TRX-EUR",
  "EGLD-EUR",
  "AVAX-EUR",
  "SOL-EUR",
  "SHIB-EUR",
  "LAZIO-EUR",
  "MATIC-EUR",
  "LINK-EUR",
  "ICP-EUR",
  "RUNE-EUR",
  "WIN-EUR",
  "VET-EUR",
  "UNI-EUR",
  "SXP-EUR",
  "HOT-EUR",
  "BTT-EUR"
]

#list of pairs to trade
tradepairs = [
  "CHZ-EUR",
  "ENJ-EUR",
  "THETA-EUR",
  "LUNA-EUR",
  "EOS-EUR",
  "XRP-EUR",
  "DOT-EUR",
  "ETH-EUR",
  "BNB-EUR",
  "XLM-EUR",
  "GRT-EUR",
  "ADA-EUR",
  "TRX-EUR",
  "EGLD-EUR",
  "AVAX-EUR",
  "SOL-EUR",
  "LAZIO-EUR",
  "MATIC-EUR",
  "LINK-EUR",
  "SHIB-EUR",
  "ICP-EUR",
  "RUNE-EUR",
  "WIN-EUR",
  "VET-EUR",
  "UNI-EUR",
  "SXP-EUR",
  "HOT-EUR",
  "BTT-EUR"
]

#amount to invest
invest_amount = 100

#percent of potential win
limit_depth = 70

#mininum win in %
minwin = 2

#use tickers
useticker = true

#use zerostrategy
usezerostrategy = false

#use strategy for rising markets
bullstrategy = false
bullwin = 1

#comma amount
[amountcomma]
BNB-EUR = "3"
DOT-EUR = "2"
XRP-EUR = "0"
ENJ-EUR = "1"
THETA-EUR = "1"
LUNA-EUR = "2"
EOS-EUR = "1"
ETH-EUR = "4"
CHZ-EUR = "0"
GRT-EUR = "0"
XLM-EUR = "0"
ADA-EUR = "1"
TRX-EUR = "0"
EGLD-EUR = "2"
AVAX-EUR = "2"
SOL-EUR = "2"
LAZIO-EUR = "2"
MATIC-EUR = "1"
LINK-EUR = "2"
SHIB-EUR = "0"
ICP-EUR = "2"
RUNE-EUR = "1"
WIN-EUR = "0"
VET-EUR = "2"
UNI-EUR = "2"
SXP-EUR = "1"
HOT-EUR = "1"
BTT-EUR = "0"

#comma price
[pricecomma]
BNB-EUR = "1"
DOT-EUR = "2"
XRP-EUR = "3"
ENJ-EUR = "3"
THETA-EUR = "3"
LUNA-EUR = "2"
EOS-EUR = "3"
ETH-EUR = "2"
CHZ-EUR = "4"
GRT-EUR = "4"
XLM-EUR = "4"
ADA-EUR = "3"
TRX-EUR = "5"
EGLD-EUR = "2"
AVAX-EUR = "2"
SOL-EUR = "2"
LAZIO-EUR = "4"
MATIC-EUR = "4"
LINK-EUR = "2"
SHIB-EUR = "8"
ICP-EUR = "2"
RUNE-EUR = "3"
WIN-EUR = "7"
VET-EUR = "5"
UNI-EUR = "2"
SXP-EUR = "3"
HOT-EUR = "6"
BTT-EUR = "6"
