# do a trace (get more output to log), true or false
do_trace = false

# trace ticker into db table yourtrace
ticker_trace = true

# sleep before candles are fetched
sleepbeforerun = 20

# location of gctcli command
gctcmd = "/home/pi/git/yourCryptoBot/exchanges/coinbase/coinbase"

wwwpath = "/var/www/html/"

# quote currency
curr_quote = "EUR"

pguser = ""
pgpassword = ""
pgdb = "yourBot"

tbtoken = ""

key_issuer = ""
key_account = ""
key_secret = ""

apikey = ""
apisecret = ""
apiclient = ""

# name of exchange
exchange_name = "coinbase"

# list of pairs
pairs = [
  "ETH-EUR",
  "ADA-EUR",
  "DOGE-EUR",
  "DOT-EUR",
  "XTZ-EUR",
  "SOL-EUR",
  "ICP-EUR",
  "EOS-EUR",
  "XLM-EUR",
  "OMG-EUR",
  "FIL-EUR",
  "RLY-EUR",
  "CRV-EUR"
]

#list of pairs to trade
tradepairs = [
  "ETH-EUR",
  "ADA-EUR",
  "DOGE-EUR",
  "DOT-EUR",
  "XTZ-EUR",
  "SOL-EUR",
  "ICP-EUR",
  "EOS-EUR",
  "XLM-EUR",
  "OMG-EUR",
  "FIL-EUR",
  "RLY-EUR",
  "CRV-EUR"
]

#amount to invest
invest_amount = 150

#percent of potential win
limit_depth = 70

#mininum win in %
minwin = 3

#use tickers
useticker = true

#use zerostrategy
usezerostrategy = false

#use strategy for rising markets
bullstrategy = false
bullwin = 1
bulltrend = 0.6

#comma amount
[amountcomma]
ETH-EUR = "5"
ADA-EUR = "2"
DOGE-EUR = "1"
DOT-EUR = "3"
XTZ-EUR = "2"
SOL-EUR = "3"
ICP-EUR = "4"
EOS-EUR = "1"
XLM-EUR = "0"
OMG-EUR = "1"
FIL-EUR = "3"
RLY-EUR = "0"
CRV-EUR = "2"

#price amount
[pricecomma]
ETH-EUR = "2"
ADA-EUR = "4"
DOGE-EUR = "4"
DOT-EUR = "3"
XTZ-EUR = "5"
SOL-EUR = "3"
ICP-EUR = "3"
EOS-EUR = "3"
XLM-EUR = "6"
OMG-EUR = "4"
FIL-EUR = "4"
RLY-EUR = "4"
CRV-EUR = "4"
