# do a trace (get more output to log), true or false
do_trace = false

# sleep before candles are fetched
sleepbeforerun = 0

# location of gctcli command
gctcmd = "/home/pi/git/yourCryptoBot/exchanges/crypto/crypto"

# path of html pages
wwwpath = "/var/www/html/"

# quote currency
curr_quote = "USDC"

pguser = ""
pgpassword = ""
pgdb = "yourBot"

tbtoken = ""

key_issuer = ""
key_account = ""
key_secret = ""

apikey = ""
apisecret = ""
apiclient = ""

# name of exchange
exchange_name = "crypto"

# list of pairs
pairs = [
  "MATIC-USDC",
  "UNI-USDC",
  "FXS-USDC",
  "XRP-USDC",
  "GHST-USDC",
  "AAVE-USDC",
  "LINK-USDC",
  "MLN-USDC",
  "DOT-USDC",
  "DAI-USDC",
  "FARM-USDC",
  "QNT-USDC",
  "ENJ-USDC",
  "CRO-USDC",
  "VET-USDC",
  "DOGE-USDC",
  "ETH-USDC",
  "POLY-USDC",
  "ADA-USDC",
  "LPT-USDC"
]

#list of pairs to trade
tradepairs = [
  "MATIC-USDC",
  "UNI-USDC",
#  "FXS-USDC",
  "XRP-USDC",
  "GHST-USDC",
  "AAVE-USDC",
  "LINK-USDC",
  "MLN-USDC",
  "DOT-USDC",
  "DAI-USDC",
  "FARM-USDC",
  "QNT-USDC",
  "ENJ-USDC",
  "CRO-USDC",
  "VET-USDC",
  "DOGE-USDC",
  "ETH-USDC",
  "POLY-USDC",
  "ADA-USDC",
  "LPT-USDC"
]

#amount to invest
invest_amount = 50

#percent of potential win
limit_depth = 70

#mininum win in %
minwin = 2

#use tickers
useticker = true

#use zerostrategy
usezerostrategy = false

#use strategy for rising markets
bullstrategy = false
bullwin = 1

#comma amount
[amountcomma]
SHIB-USDC = "0"
MATIC-USDC = "1"
UNI-USDC = "3"
FXS-USDC = "2"
XRP-USDC = "1"
GHST-USDC = "2"
AAVE-USDC = "4"
LINK-USDC = "3"
MLN-USDC = "3"
DOT-USDC = "3"
DAI-USDC = "2"
FARM-USDC = "4"
QNT-USDC = "4"
ENJ-USDC = "2"
CRO-USDC = "3"
VET-USDC = "0"
DOGE-USDC = "1"
ETH-USDC = "5"
POLY-USDC = "1"
ADA-USDC = "1"
LPT-USDC = "3"

#comma price
[pricecomma]
SHIB-USDC = "9"
MATIC-USDC = "5"
UNI-USDC = "3"
FXS-USDC = "4"
XRP-USDC = "5"
GHST-USDC = "4"
AAVE-USDC = "2"
LINK-USDC = "3"
MLN-USDC = "3"
DOT-USDC = "3"
DAI-USDC = "4"
FARM-USDC = "2"
QNT-USDC = "2"
ENJ-USDC = "4"
CRO-USDC = "5"
VET-USDC = "6"
DOGE-USDC = "5"
ETH-USDC = "2"
POLY-USDC = "5"
ADA-USDC = "5"
LPT-USDC = "3"

